import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Boss Money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div>
        <h2 className="p-5 text-lg">Welcome User</h2>

      </div>
    </>
  );
};

export default Home;
