import type { NextPage } from "next";
import dynamic from 'next/dynamic';
import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation";

const Dropdown = dynamic(() => import('../components/dropdown'));
const DropdownField = dynamic(() => import('../components/dropdown-field'));


const data = [
  {
    title: "item1",
    price: 8000,
  },
  {
    title: "item2",
    price: 8500,
  },
]

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Boss Money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="m-5">
        <h2 className="py-3 text-lg">Welcome User</h2>
        <Dropdown title="Income">
          {data.map((item) => <DropdownField item={item} key={item.title} />)}
        </Dropdown>
      </div>
    </>
  );
};

export default Home;
